use std::sync::RwLock;

use async_trait::async_trait;
use serde_json::{json, Value};

use crate::drivers::Driver;
use crate::error::AppError;
use crate::model::{ColumnInfo, IndexInfo, QueryResult, TableInfo};

pub struct MongoDriver {
    client: mongodb::Client,
    db: RwLock<String>,
}

impl MongoDriver {
    pub fn new(client: mongodb::Client, db: String) -> Self {
        Self { client, db: RwLock::new(db) }
    }
    fn current_db(&self) -> String {
        self.db.read().unwrap().clone()
    }
}

/// Parse a simple SELECT generated by loadTableData:
/// SELECT * FROM "col" [WHERE ...] [ORDER BY "f" ASC|DESC] LIMIT n OFFSET n
struct ParsedMongo {
    collection: String,
    limit: u32,
    skip: u32,
    sort_field: Option<String>,
    sort_asc: bool,
}

fn parse_mongo_select(sql: &str) -> Option<ParsedMongo> {
    let upper = sql.to_uppercase();
    // Collection name after FROM
    let from_idx = upper.find("FROM ")? + 5;
    let after_from = sql[from_idx..].trim();
    let collection = if after_from.starts_with('"') {
        let end = after_from[1..].find('"')? + 1;
        after_from[1..end].to_string()
    } else {
        after_from.split_whitespace().next()?.to_string()
    };

    // LIMIT
    let limit = upper.find("LIMIT ")
        .map(|pos| sql[pos + 6..].split_whitespace().next()
            .and_then(|s| s.parse().ok()).unwrap_or(50))
        .unwrap_or(50);

    // OFFSET
    let skip = upper.find("OFFSET ")
        .map(|pos| sql[pos + 7..].split_whitespace().next()
            .and_then(|s| s.parse().ok()).unwrap_or(0))
        .unwrap_or(0);

    // ORDER BY
    let (sort_field, sort_asc) = if let Some(pos) = upper.find("ORDER BY ") {
        let after = sql[pos + 9..].trim();
        let field = if after.starts_with('"') {
            after[1..].find('"').map(|end| after[1..=end].to_string())
        } else {
            None
        };
        let asc = !upper.contains(" DESC");
        (field, asc)
    } else {
        (None, true)
    };

    Some(ParsedMongo { collection, limit, skip, sort_field, sort_asc })
}

#[async_trait]
impl Driver for MongoDriver {
    async fn ping(&self) -> Result<(), AppError> {
        self.client.list_database_names().await.map(|_| ()).map_err(|e| AppError::new(e.to_string()))
    }

    async fn set_database(&self, db: &str) -> Result<(), AppError> {
        *self.db.write().unwrap() = db.to_string();
        Ok(())
    }

    async fn list_databases(&self) -> Result<Vec<String>, AppError> {
        let system = ["admin", "config", "local"];
        let mut names = self.client
            .list_database_names()
            .await
            .map_err(|e| AppError::new(e.to_string()))?;
        names.retain(|n| !system.contains(&n.as_str()));
        names.sort();
        Ok(names)
    }

    async fn list_tables(&self) -> Result<Vec<TableInfo>, AppError> {
        let database = self.client.database(&self.current_db());
        let names = database
            .list_collection_names()
            .await
            .map_err(|e| AppError::new(e.to_string()))?;
        let mut sorted = names;
        sorted.sort();
        Ok(sorted.into_iter().map(|name| TableInfo { name }).collect())
    }

    async fn describe_table(&self, table: &str) -> Result<Vec<ColumnInfo>, AppError> {
        // Sample up to 10 documents to discover field names
        use mongodb::bson::Document;
        let collection: mongodb::Collection<Document> = self.client
            .database(&self.current_db())
            .collection(table);

        let mut cursor = collection
            .find(mongodb::bson::doc! {})
            .limit(10)
            .await
            .map_err(|e| AppError::new(e.to_string()))?;

        let mut field_set: std::collections::LinkedList<String> = std::collections::LinkedList::new();
        let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();

        use futures_util::StreamExt;
        while let Some(doc) = cursor.next().await {
            if let Ok(doc) = doc {
                for key in doc.keys() {
                    if seen.insert(key.to_string()) {
                        field_set.push_back(key.to_string());
                    }
                }
            }
        }

        Ok(field_set.into_iter().map(|name| ColumnInfo {
            is_pk: name == "_id",
            data_type: if name == "_id" { "ObjectId".into() } else { "mixed".into() },
            nullable: name != "_id",
            name,
        }).collect())
    }

    async fn list_indexes(&self, table: &str) -> Result<Vec<IndexInfo>, AppError> {
        use mongodb::bson::Bson;
        use futures_util::StreamExt;
        use mongodb::bson::Document;

        let coll: mongodb::Collection<Document> = self.client.database(&self.current_db()).collection(table);
        let mut cursor = coll.list_indexes().await
            .map_err(|e| AppError::new(e.to_string()))?;

        let mut indexes = Vec::new();
        while let Some(model) = cursor.next().await {
            let model = model.map_err(|e| AppError::new(e.to_string()))?;
            let name = model.options.as_ref()
                .and_then(|o| o.name.as_deref())
                .unwrap_or("unknown")
                .to_string();
            let is_unique = model.options.as_ref()
                .and_then(|o| o.unique)
                .unwrap_or(false);
            let columns = model.keys.iter().map(|(k, v)| {
                let dir = match v {
                    Bson::Int32(1) | Bson::Int64(1) => "asc",
                    _ => "desc",
                };
                format!("{}: {}", k, dir)
            }).collect::<Vec<_>>().join(", ");
            indexes.push(IndexInfo {
                name, columns, is_unique, index_type: "compound".to_string(),
            });
        }
        Ok(indexes)
    }

    async fn run_query(&self, sql: &str) -> Result<QueryResult, AppError> {
        use mongodb::bson::{doc, Document, Bson};
        use futures_util::StreamExt;

        let db = self.current_db();

        let parsed = parse_mongo_select(sql)
            .ok_or_else(|| AppError::new(
                "MongoDB only supports simple collection queries from the table view. \
                 Use the sidebar to browse collections."
            ))?;

        let collection: mongodb::Collection<Document> = self.client
            .database(&db)
            .collection(&parsed.collection);

        // Build find options
        let mut find = collection.find(doc! {});
        find = find.limit(parsed.limit as i64).skip(parsed.skip as u64);
        if let Some(field) = &parsed.sort_field {
            let direction = if parsed.sort_asc { 1i32 } else { -1i32 };
            find = find.sort(doc! { field: direction });
        }

        let mut cursor = find.await
            .map_err(|e| AppError::new(e.to_string()))?;

        let mut all_docs: Vec<Document> = Vec::new();
        while let Some(doc) = cursor.next().await {
            all_docs.push(doc.map_err(|e| AppError::new(e.to_string()))?);
        }

        if all_docs.is_empty() {
            return Ok(QueryResult { columns: vec![], rows: vec![], rows_affected: None });
        }

        // Collect all field names (union across sampled docs)
        let mut field_set: std::collections::LinkedList<String> = std::collections::LinkedList::new();
        let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
        // _id always first
        if seen.insert("_id".to_string()) { field_set.push_back("_id".to_string()); }
        for doc in &all_docs {
            for key in doc.keys() {
                if key != "_id" && seen.insert(key.to_string()) {
                    field_set.push_back(key.to_string());
                }
            }
        }
        let columns: Vec<String> = field_set.into_iter().collect();

        let rows = all_docs.iter().map(|doc| {
            let mut map = serde_json::Map::new();
            for col in &columns {
                let val = match doc.get(col.as_str()) {
                    None => Value::Null,
                    Some(Bson::Null) => Value::Null,
                    Some(Bson::Boolean(b)) => Value::Bool(*b),
                    Some(Bson::Int32(n)) => json!(n),
                    Some(Bson::Int64(n)) => json!(n),
                    Some(Bson::Double(n)) => json!(n),
                    Some(Bson::String(s)) => Value::String(s.clone()),
                    Some(Bson::ObjectId(oid)) => Value::String(oid.to_hex()),
                    Some(Bson::DateTime(dt)) => Value::String(dt.to_string()),
                    Some(other) => Value::String(other.to_string()),
                };
                map.insert(col.clone(), val);
            }
            Value::Object(map)
        }).collect();

        Ok(QueryResult { columns, rows, rows_affected: None })
    }
}
